// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDqRW27gPgmmyFCKaVN2ehL-DUWnQ4qNQs',
    appId: '1:561466249078:web:c46c8c7a80492ae087f457',
    messagingSenderId: '561466249078',
    projectId: 'lo2ta-b7577',
    authDomain: 'lo2ta-b7577.firebaseapp.com',
    storageBucket: 'lo2ta-b7577.firebasestorage.app',
    measurementId: 'G-BJ3N26JL2G',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBaowRNm0pBCILK_jlvlRNPPbOkQAlPC20',
    appId: '1:561466249078:android:93043409a493982b87f457',
    messagingSenderId: '561466249078',
    projectId: 'lo2ta-b7577',
    storageBucket: 'lo2ta-b7577.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCaRSGjgjjPGaWCk8csin_eBGLtKud9wik',
    appId: '1:561466249078:ios:4e9a5c4a683a27bb87f457',
    messagingSenderId: '561466249078',
    projectId: 'lo2ta-b7577',
    storageBucket: 'lo2ta-b7577.firebasestorage.app',
    iosBundleId: 'com.lo2ta.lo2ta',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCaRSGjgjjPGaWCk8csin_eBGLtKud9wik',
    appId: '1:561466249078:ios:4e9a5c4a683a27bb87f457',
    messagingSenderId: '561466249078',
    projectId: 'lo2ta-b7577',
    storageBucket: 'lo2ta-b7577.firebasestorage.app',
    iosBundleId: 'com.lo2ta.lo2ta',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDqRW27gPgmmyFCKaVN2ehL-DUWnQ4qNQs',
    appId: '1:561466249078:web:93a175788bd5c0f787f457',
    messagingSenderId: '561466249078',
    projectId: 'lo2ta-b7577',
    authDomain: 'lo2ta-b7577.firebaseapp.com',
    storageBucket: 'lo2ta-b7577.firebasestorage.app',
    measurementId: 'G-ZLFR7LJXXS',
  );
}
